### PR TITLE
Fix staking bugs & release preparation

### PR DESCRIPTION
**Pull request by ERussel**
- move to dashboard after parachain staking redeem all #85ztzapq0
- add existential deposit validation for nomination pool unstake, claim and redeem operations #8692t0fat
- fix staking details shimmering #85ztyd3wp
- set payload size = 512 for multiframe QR code #8692rur7h
- bump xcm config #8692t19ae

### CODE REVIEW

**Comment by stepanLav** [comment]
Task linked: [CU-85ztyd3wp iOS. Fix shimmering display for your pool](https://app.clickup.com/t/85ztyd3wp)

**Comment by stepanLav** [comment]
Task linked: [CU-85ztzapq0 iOS. Stays on staking details after redeem all](https://app.clickup.com/t/85ztzapq0)

**Comment by stepanLav** [comment]
Task linked: [CU-8692t0fat iOS. Add eD validation on nomination pool flows](https://app.clickup.com/t/8692t0fat)

**Comment by stepanLav** [comment]
Task linked: [CU-8692t19ae iOS. Bump xcm config version to v5](https://app.clickup.com/t/8692t19ae)

**Comment by stepanLav** [comment]
Task linked: [CU-8692rur7h iOS. Set reccomended max payload size for QR generation](https://app.clickup.com/t/8692rur7h)

**Review by lynx56 — APPROVED** [review]

**Pull request merged**
