### PR TITLE
7.8.0 bug fixes and localization

### PR DESCRIPTION
**Pull request by ERussel**
- update add staking proxy flow texts #8693p1hw7
- enable proxieds for add staking proxy account selection #8693nrwmb
- delegation already exists fix #8693q9ezu
- fix links tap #8693nqua4
- syncronise localize

### CODE REVIEW

**Comment by stepanLav** [comment]
Task linked: [CU-8693p1hw7 iOS. Update proxy text strings](https://app.clickup.com/t/8693p1hw7)

**Comment by stepanLav** [comment]
Task linked: [CU-8693q9ezu iOS. Delegation already exists for not delegating accounts](https://app.clickup.com/t/8693q9ezu)

**Comment by stepanLav** [comment]
Task linked: [CU-8693nrwmb iOS. Enable proxieds on add to staking proxy](https://app.clickup.com/t/8693nrwmb)

**Comment by stepanLav** [comment]
Task linked: [CU-8693nqua4 iOS. I have an error button is not reacting](https://app.clickup.com/t/8693nqua4)

**Review by lynx56 — APPROVED** [review]

**Pull request merged**
